[package]
name = "bevy_p2p"
version = "0.1.0"
edition = "2024"
description = "a steam/iroh p2p networking crate"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bgkillas/bevy_p2p"

[features]
default=[]
steam=["dep:steamworks"]

[dependencies]
steamworks = {version = "0.13.1", optional = true}
iroh = "1.0.3"
bevy_ecs = {version = "0.19.1", default-features = false}
bevy_app = {version = "0.19.1", default-features = false}
bevy_log = {version = "0.19.1", default-features = false}
bitcode = {git = "https://github.com/SoftbearStudios/bitcode", branch = "custom_encoder"}
rustc-hash = "2.1.3"
zerocopy = "0.9.0-alpha.0"
tokio = {version = "1.53.1", features = ["sync"]}
bimap = "0.6.3"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen-futures = "0.4.77"
tokio_with_wasm = {version = "0.10.1", features = ["macros", "rt", "sync"]}

[dev-dependencies]
bevy = {version = "0.19.1", default-features=false, features = ["debug"]}

[lints.clippy]
pedantic = {level = "warn", priority = -1}
shadow_reuse = "warn"
unused_trait_names = "warn"
str_to_string = "warn"
missing_panics_doc = "allow"
missing_errors_doc = "allow"
too_many_lines = "allow"
missing_fields_in_debug = "allow"
missing_safety_doc = "allow"
similar_names = "allow"
too_many_arguments = "allow"
type_complexity = "allow"
missing_inline_in_public_items = "allow"
needless_pass_by_value = "allow"

cast_precision_loss = "allow"
as_conversions = "allow"
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
